### ISSUE TITLE
Request throwing error when status code is 500

### ISSUE THREAD

**Issue by matheussss1** [japa/api-client#3]
### Package version

9.1.0

### Describe the bug
@thetutlage 

Why does the client throws an error when the request return a 500 status code?

It makes no sense to me, [including the fact that at the docs we have this:](https://japa.dev/docs/plugins/api-client#hasfatalerror)

```
if (response.hasFatalError()) {
  response.error()
}
```

How could i access reponse.hasFatalError if when the fatal error occurs the client just throw an error and the test stop?

Even if i make a .catch block, the returned value has a prototype of Error, not ApiResponse

**Comment by andrejfidelleanix** [comment]
Throwing for 500+ errors is weird. They can be valid responses returned intentionally (a handled and/or expected error you don't want to report to the user).

Also, not having the ApiResponse object to assert with is worse DX, in my opinion. If you want to ensure the request isn't 500, you can just assert so on the ApiResponse. If you want to assert something about the response (for example: "Server is down for maintenance" vs. "Server is temporarily overloaded" for 503), it's easier to assert bodyContains.

**Comment by thetutlage** [comment]
We have received quite a few requests for this, so I think many people find throwing exceptions a bit weird. Should we handle 500 exceptions the same way as we handle other exceptions? @RomainLanz @Julien-R44  What you guys think?

**Comment by Julien-R44** [comment]
Yup, i agree. would be better to be able to make assertions instead of wrapping the test with a try/catch or whatever

**Comment by thetutlage** [comment]
Okay, let's do it then. It will be a breaking change.

**Comment by nadlgit** [comment]
Hi, running into this issue, change is it still planned ? Is there a workaround meanwhile ?
